### ISSUE TITLE
Chromium is hard coded

### ISSUE THREAD

**Issue by firecat53** [carnager/rofi-pass#1]
How about reading $BROWSER from ENV or allowing setting BROWSER in the config file?

**Comment by foxxx0** [comment]
good idea, we're still in the very early stages and still in the process of modularising the whole script. there will be options made user-configurable in a config file soon-ish.

**Comment by carnager** [comment]
@firecat53 I am not sure. wouldn't xdg-open be the better way?

**Comment by carnager** [comment]
fixed in 69fb66aab30025f8f3d865fc4180404dfda9b4be
