### ISSUE TITLE
Fail on moving parsers if no config dir was created in $HOME

### ISSUE THREAD

**Issue by Narrat** [carnager/rofi-pass#10]
Currently testing this, with the default config from /etc (so no files copied into my home dir)
And invoking rofi creates this message:

>$ LANG=C rofi-pass
mkdir: cannot create directory '/home/omnius/.config/rofi-pass/parsers': No such file or directory
cp: target '/home/omnius/.config/rofi-pass/parsers' is not a directory

Is this intended behaviour? (like it's unnecessary to copy this if the user didn't create a config. Still the error messages aren't that nice)

**Comment by carnager** [comment]
Yes right, this is ugly, but to be honest, the whole function to parse browsers for current url is. 

I will fix this tonight and at the same time think about what to do about the parsers themselves

**Comment by carnager** [comment]
I removed the option to get URL from open browser windows for now. It was never working properly anyway.

**Comment by Narrat** [comment]
For Firefox the alternative could be to parse the content of $PROFILE/sessionstore-backups/recovery.js
Dunno how easy it is to parse json in a sane way, but the active tab could be marked as such.
Although this still has the following disadvantages I currently can think of:
 * Getting the active profile path
 * delay between file updates (~15 secs)
 * Dunno about the result if sessionstore is disabled

Dunno if there is an additional place where this info get stored (if then it's most likely in one of the sqlites)

**Comment by carnager** [comment]
to be honest. using the provided addpass script is much faster than handling the menu :)

**Comment by Narrat** [comment]
:D 
One last note then ;)
I grepped for wmctrl after the parsers got removed and the only result was the README.md. So if this gone shouldn't it be removed from needed Deps (README.md and PKGBUILD)?

**Comment by carnager** [comment]
yeah, thanks. fixed
