### ISSUE TITLE
root dir is forcing an header again

### ISSUE THREAD

**Issue by Rahtgaz** [carnager/rofi-pass#100]
With the new `root` option, rofi-pass is again forcing an header (#83) that, in this case, is completely redundant for users with just one root.

It would be great if we could choose between showing or not the root dir header.  Or, perhaps better, only show the header if the option is set with more than one root.

**Comment by carnager** [comment]
It's not *that* easy. You could still have provided a single root via --root option, so only showing it on multi roots is not an option.

Have to think about a good way to handle this.

**Comment by Rahtgaz** [comment]
> You could still have provided a single root via --root option, so only showing it on multi roots is not an option.

But If I explicitly provide a single root, does it make sense to display it to the user? I would take it that the user is fully aware of the non-default location of his password store. He doesn't need to be reminded of the fact every single time rofi-pass is invoked. There is no concrete benefit to it.

**Comment by carnager** [comment]
actually I was overcomplicating things. The solution is really simple... fix coming in a second.
