### ISSUE TITLE
Opening by keyboard shortcut do not open pinentry

### ISSUE THREAD

**Issue by gmhafiz** [carnager/rofi-pass#110]
Pressing keyboard shortcut (Mod4+p) to run rofi-pass opens up the menu but pressing Alt-1 to autotype will just prints out my username and no pinentry showing up.

However, typing rofi-pass from terminal works. It will both open the menu and Alt+1 will autotype for me after entering correct password in pinentry-gtk-2.

OS: Ubuntu 16.04
pass:   v1.6.5
rofi-pass: latest commit https://github.com/carnager/rofi-pass/commit/3abb5ec3240127de1cfaf92086da6f861c3bea1c

Not sure if it is gpg related but my gpg-agent.conf file is pretty normal:
```shell
default-cache-ttl 300
max-cache-ttl 9999
```

My config file:

```shell
# permanently set alternative root dir
# root=/path/to/root

# rofi command. Make sure to have "$@" as last argument
_rofi () {
    rofi -no-auto-select -kb-row-tab '' -kb-accept-entry "!Return" "$@"
}

# xdotool needs the keyboard layout to be set using setxkbmap
# You can do this in your autostart scripts (e.g. xinitrc)

# If for some reason, you cannot do this, you can set the command here.
# and set fix_layout to true
fix_layout=true

layout_cmd () {
  setxkbmap us
}

# fields to be used
URL_field='url'
USERNAME_field='user'
AUTOTYPE_field='autotype'

# delay to be used for :delay keyword
delay=2

## Programs to be used
# Editor
EDITOR='vim -f'

# Browser
BROWSER='chromium'

## Misc settings

default_do='autopass' # menu, autotype, copyPass, typeUser, typePass, copyUser, copyUrl, viewEntry, typeMenu, actionMenu, copyMenu, openUrl
auto_enter='false'
notify='false'
default_autotype='user :tab pass'

# color of the help messages
# leave empty for autodetection
help_color="#4872FF"

# Clipboard settings
# Possible options: primary, clipboard, both
clip=primary

# Options for generating new password entries
# default_user is also used for password files that have no user field.
#default_user=john_doe
#default_user2=mary_ann
#password_length=12

# Custom Keybindings
autotype="Alt+1"
type_user="Alt+2"
type_pass="Alt+3"
open_url="Alt+4"
copy_name="Alt+u"
copy_url="Alt+l"
copy_pass="Alt+p"
show="Alt+o"
copy_entry="Alt+2"
type_entry="Alt+1"
copy_menu="Alt+c"
action_menu="Alt+a"
type_menu="Alt+t"
help="Alt+h"
switch="Alt+x"
insert_pass="Alt+n"
`

**Comment by carnager** [comment]
Sounds to me that your window manager has a different environment to your terminal.

**Comment by gmhafiz** [comment]
Awesome. Fixed it by changing the exec in Keyboard Shortcut settings from

`rofi-pass` to `env GNUPGHOME=<my_folder>/.gnupg rofi-pass`

I have custom path to $GNUPGHOME. 

Mate DE seems to not pick this up. Interestingly, i3 works without setting env variable with `bindsym --release $mod+p exec --no-startup-id rofi-pass`

**Comment by carnager** [comment]
glad you fixed it

**Comment by KaratasFurkan** [comment]
I had the same issue, fixed it by creating `~/.gnupg/gpg-agent.conf` with this in it:
```sh
pinentry-program /usr/bin/pinentry-rofi
```
(you can use some other pinentry program e.g. `pinentry-gtk-2`)

And restart gpg-agent with this command to apply chages:
```sh
pkill -HUP gpg-agent
```
