### ISSUE TITLE
Passwords with the number sign in them ('#') do not paste correctly

### ISSUE THREAD

**Issue by benoliver999** [carnager/rofi-pass#114]
Let's say I have a password:

    ieXXji%twdfj#j99u

If I paste it with rofi-pass it comes out as:

    ieXXji%twdfjj99u

**Comment by benoliver999** [comment]
This also appears to be the case with a backslash `\`

**Comment by carnager** [comment]
let me quote the FAQ:

```
rofi pass prints garbage instead of my actual passes

Make sure to run setxkbmap <language> <variant> at the start of your Xorg session.
```

**Comment by benoliver999** [comment]
Aaagh I'm sorry. I saw this and thought I was already setting it, but no, it was `XkbLayout`

**Comment by carnager** [comment]
Yeah, setting it via xorg config will not work, for whatever reason
