### ISSUE TITLE
Otp field is not visible

### ISSUE THREAD

**Issue by ReekyMarko** [carnager/rofi-pass#115]
First of all, thanks for your efforts on creating this wonderful program! I'm using it every day and wouldn't switch away if somebody gave me a million dollars 😄 

So, my problem is that I can't get the otp field to show up in `rofi-pass`. I have my otp's setup and they work flawlessly with `pass otp`. I presume this is something I have to enable in the config, but I couldn't find any documentation for doing that. I tried to add a field called OTP_field in /etc/rofi-pass.conf, but it makes no difference.

**Comment by carnager** [comment]
@moviuro your help is needed, since I have no clue at all about how otp works :)

**Comment by moviuro** [comment]
What does the OTP line look like in the pass file?

```
    otpauth://<blabla> # should work
```
---
```
    otp_method: /opt/obscure-otp-generator/oog --some-option some args # should also work
```

What commit are you at? Commits before 3abb5ec3240127de1cfaf92086da6f861c3bea1c don't have the functionality, and even the latest tag (1.5.3 as of writing) does not include it.

**Comment by ReekyMarko** [comment]
I'm using the package `rofi-pass` from the Arch User Repository. I wasn't aware that this was such a new feature, maybe I should try `rofi-pass-git` instead.

**Comment by ReekyMarko** [comment]
Just installed `rofi-git` and all is fine! Closing.

**Comment by ReekyMarko** [comment]
Just installed rofi-git and all is fine! Closing.

**Comment by carnager** [comment]
I probably should make a new release then :)

**Comment by dmarcoux** [comment]
I just had the same "issue" before realizing that I'm using the release `1.5.3`. A new release would be great and thank you for this amazing tool!
