### ISSUE TITLE
rofi-pass changes special chars to something else

### ISSUE THREAD

**Issue by BrutalBirdie** [carnager/rofi-pass#131]
I had the issue more then once that rofi-pass would change # to §, _ to ?

example password
./#The_Towers_of_rohan\#. will get changed to ./#The_Towers?of?rohan\#.
./#Fo0O\#. to ./#Fo0O\§.

**Comment by carnager** [comment]
read the FAQ

## FAQ

### rofi pass prints garbage instead of my actual passes

Make sure to run `setxkbmap <language> <variant>` at the start of your Xorg
session.
