### ISSUE TITLE
previous_root, next_root keybindings conflict with default rofi keybindings, preventing start

### ISSUE THREAD

**Issue by klaasb** [carnager/rofi-pass#132]
Rofi fails to start now when key combinations are bound to multiple commands.
By default Shift+Left and Shift+Right are bound to `rofi.kb-mode-previous` and `rofi.kb-mode-next` respectively.

**Comment by carnager** [comment]
I have a default rofi (1.5.1) and have no conflicts. Anyway, since this is easily worked around via config, i dont want to hardcode any options into rofi-pass itself.

Just edit the _rofi function in config file. Something like:

```
_rofi () {
    rofi -i -no-auto-select -kb-mode-previous "" -kb-mode-next "" "$@"      
}
```
