### ISSUE TITLE
Several "autotype" actions

### ISSUE THREAD

**Issue by raphaelfournier** [carnager/rofi-pass#133]
I would like to have the possibility to define several ways to "autotype" the information from a pass file. Typically, I have stored my credential for a gitlab server and would like to have the standard autotype for the web interface (like for any other website, `autotype: login :tab pass :enter`) and an alternative one for the command line prompt, which requires :enter between login and pass instead of :tab. 

I would see it as a new configuration option but I am not a specialist of rofi's code.

Thanks for your work!

(it would be an enhancement issue, and I may try to implement it before September if no one does)

**Comment by carnager** [comment]
I see where you are coming from. Personally I simply have foobar_web and foobar_blub files for such cases. That being said, if it's a clean patch, I'd happily merge it.
