### ISSUE TITLE
Missing entry in menu from default_do

### ISSUE THREAD

**Issue by carlf** [carnager/rofi-pass#134]
I'm not sure a better way to describe this. When I bring up the 'menu' action set in default_do, I get a list of the usual actions (autotype, pass, url, and username) but there is an empty entry where I think user would go. I assume this is because my entries use username for the username instead of user. An example of one of my pass files:

```
pass123
---
username: me@foo.com
url: https://www.foobar.com
```

I have the following in ~/.config/rofi-pass/config

```
USERNAME_field='username'
```

I've been pulling my hair out trying to see where this blank entry is coming from and what should be there. Anyone have any suggestions?

**Comment by carnager** [comment]
Hmm, I cannot reproduce this. Used your test file:

![rofi-2018-07-05-0046-00000](https://user-images.githubusercontent.com/3321178/42295672-13d0dea4-7fed-11e8-943e-bd98b766b8f5.png)

**Comment by carlf** [comment]
This looks like it was a downstream problem. That fix was not pulled in because the AUR package I was using pointed to git+https://git.53280.de/rofi-pass which seems to not have the update you reference. I pulled from github directly and my problem went away. Thanks and sorry for the needless interrupt.

**Comment by carnager** [comment]
Right. I switched the PKGBUILD to use github now.
