### ISSUE TITLE
Is there a way to enter in Bookmark mode instead PW store by default?

### ISSUE THREAD

**Issue by 2Belette** [carnager/rofi-pass#135]
Intead of launching rofi-pass, switching to Bookmark mode is there a way to land in Bookmark mode when launching rofi-pass (and switching to PW store if needed)

**Comment by moviuro** [comment]
https://github.com/carnager/rofi-pass/blob/4ed851e051dffa7ad7bf893281d2c9da76112c30/rofi-pass#L759 Probably ?

**Comment by 2Belette** [comment]
Thanks!
