### ISSUE TITLE
Default username

### ISSUE THREAD

**Issue by dvogt23** [carnager/rofi-pass#145]
Hello guys, i have some trouble with my usernames. My password-store is organized like `somesite.com/username` with the password as content. Is it possible to set the default username fallback to the last part of my password entries? Or i have to add a new entry for every password in my store :-1:

**Comment by moviuro** [comment]
See #140 and https://github.com/carnager/rofi-pass/blob/8bf4d479585bc692f13edf817cd11c1848086906/README.md#user-filename-as-user

**Comment by dvogt23** [comment]
Oh nice, thanks.
