### ISSUE TITLE
Add config variable for pass clearing delay

### ISSUE THREAD

**Issue by ofpau** [carnager/rofi-pass#146]
At this moment the delay before clearing a password from the keyboard is hardcoded to 45 seconds. I think it's more convenient to have it in a variable of the config file. 

I'll probably submit a PR with that modification, if you think it may be interesting to other users.

**Comment by carnager** [comment]
I agree... just send a PR

**Comment by ofpau** [comment]
Thanks for your prompt answer and merging. Keep up the good work! This script is really useful.
