### ISSUE TITLE
Wayland Support

### ISSUE THREAD

**Issue by lifranc** [carnager/rofi-pass#151]
Recently switched to wayland and the only clipboard bug left is with rofi-pass.

Neovim works using [wl-clipboard](https://github.com/bugaevc/wl-clipboard)
Perhaps rofi-pass can use it for wayland support?

**Comment by carnager** [comment]
Basically rofi-pass only works with XWayland clients anyway, so there are lots of issues having to be fixed before. But this is nothing that can be done on my side, rofi itself or even worse the individual compositors have to add support for the way rofi works. I will leave this open though, but don't expect Wayland support anytime soon.

**Comment by lifranc** [comment]
You can close I won't pursue this- we'll change the pgp stack for saltpack anyhow.
