### ISSUE TITLE
clipboard is empty

### ISSUE THREAD

**Issue by verajosemanuel** [carnager/rofi-pass#184]
installed rofi-pass in Ubuntu i3wm
rofi is reading all my password files properly but when choosing to type a pass, nothing happened and clipboard is empty

Tried to use Alt+3 keybinding but to no avail. Nothing is tiped and clipboard is empty

**Comment by carnager** [comment]
Make sure that you have all dependencies installed. xclip and xdotool are a necessity

**Comment by verajosemanuel** [comment]
That did the trick. Thanks!
