### ISSUE TITLE
@ symbol not displayed when used in user field

### ISSUE THREAD

**Issue by justmeandopensource** [carnager/rofi-pass#188]
Hi,

I am using below command to store a password entry.
```
addpass --name "github.com" +user "test@example.com"
```
The entry gets added. But when I use **rofi-pass** to print the username, it prints
```
testqexample.com
```
For some reason the '@' symbol is replaced with 'q'.
When I use **pass** command, the username is displayed correctly.
```
pass github.com
```

Thanks,
Venkat

**Comment by moviuro** [comment]
Did you read the FAQ: https://github.com/carnager/rofi-pass#rofi-pass-prints-garbage-instead-of-my-actual-passes ?

**Comment by carnager** [comment]
closing because this is a xdotool issue which can be worked around as mentioned in FAQ
