### ISSUE TITLE
Rofi-pass doesnt create new entries?

### ISSUE THREAD

**Issue by thepenguinthatwants** [carnager/rofi-pass#193]
Hi!
I've suddenly lost ability to create new password entries.

But I can still use rofi-pass to edit existing password files and save them.
I tried to do it taking out my ./config/rofi-pass/config  but it still didnt work.

Wondering if there are any verbose mode to check whats wrong.

**Comment by thepenguinthatwants** [comment]
addpass --name "My new Site" +user "zeltak" +branch "branch" +custom "foobar" +autotype "branch :tab user :tab pass"

didnt create entry weird.

**Comment by carnager** [comment]
Just to mention it: There is Alt+n which gives you a UI for creating new entries, too
