### ISSUE TITLE
Generate new passwords using "pass generate"

### ISSUE THREAD

**Issue by somini** [carnager/rofi-pass#196]
I can't seem to be able to generate new passwords.

Here's what I tried:
- Open `rofi-pass`
- Write the name of the new password ("New" in this case)
- `Alt-A 5`(Generate new Password)
- Navigate the interactive UI (Use Symbols, define a length)
- Get an error:

```sh
$  rofi-pass
Error: New is not in the password store.
gpg: can't open '$PASSWORD_STORE/New.gpg': No such file or directory
gpg: decrypt_message failed: No such file or directory
Could not reencrypt new password.
```

I see that generating a new password doesn't trigger the pinentry for GPG, but if the keyring is unlocked, this problem remains. This is probably related to the GPG error above.

Since the interactive UI matches the `pass` features, I assumed this was just shelling out to `pass generate [ --no-symbols, -n ] [ --clip, -c ] [ --in-place, -i | --force, -f ] pass-name [pass-length]`, which works for me. This seems to work for existing passwords, but not for new ones.

**Comment by carnager** [comment]
You are misunderstanding the function. This option is to generate a new password for an existing entry.

**Comment by somini** [comment]
> To add a new entry to your store, hit Alt+n

Duh! Thanks for that, I did not read the documentation properly. :fearful:
