### ISSUE TITLE
keepass2pass.py fails

### ISSUE THREAD

**Issue by gregf** [carnager/rofi-pass#2]
python keepass2pass.py -f ~/keepass.xml
[>>>>] Importing passwords from file /home/gregf/keepass.xml
[INFO] Root path: None
Traceback (most recent call last):
  File "keepass2pass.py", line 141, in <module>
    main(sys.argv[1:])
  File "keepass2pass.py", line 135, in main
    import_passwords(xml_file, root_path)
  File "keepass2pass.py", line 94, in import_passwords
    root_group = root.find('Group')
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by carnager** [comment]
just to clarify: this is a keepass2 xml file, yes?

**Comment by gregf** [comment]
To be clear I'm a idiot that can't read. It was keypass v1. Thanks!
