### ISSUE TITLE
Send notification after typing

### ISSUE THREAD

**Issue by pigmonkey** [carnager/rofi-pass#21]
I find myself frequently using rofi-pass to type credentials into things that do not echo (ie, a sudo prompt). I know typing takes a second or two, but because I can't see it working and there is no notification upon completion, I'm never sure when it is done. Generally I end up telling rofi-pass to type the entry and then counting to 5 in my head before hitting return.

It would be nice if rofi-pass could notify the user when typing is complete via `notify-send`, just like it does when a password has been copied. This should probably be a configurable option that defaults to off, since it would get annoying if you predominantly use rofi-pass to type credentials into things that echo the typing, like most GUI apps.

**Comment by carnager** [comment]
added in a21e1b9fb3c5b63d8342593dc4939c2f67d90fcc 

Just put `notify:  true` in the password files you want to have notifications for.

**Comment by pigmonkey** [comment]
I'd rather be able to make it a universal option in the rofi-pass config, rather than per entry.

**Comment by carnager** [comment]
ok, i added a global "notify=true/false" option for config file, which can be overridden individually in password files

**Comment by pigmonkey** [comment]
Perfect! It works great. Thanks.
