### ISSUE TITLE
rofi-pass dosen't prompt anything in terminal and basically any input.

### ISSUE THREAD

**Issue by Khodesaeed** [carnager/rofi-pass#217]
Hi,
I've installed and configured rofi and rofi-pass for not too long, but recently when I want to fill any form or any input, it doesn't works (Not even in terminal).
I couldn't find any error log except this one: 
`$ rofi-pass --show-last`:
`/usr/bin/rofi-pass: line 573: stuff["${_id}"]: bad array subscript `

UPDATE: I think the problem is bash v5, how can I solve this problem?

**Comment by thepenguinthatwants** [comment]
I am using bash 5.1.16 and it works.

**Comment by Khodesaeed** [comment]
I didn't find any solution. so I guess we can close this issue.
