### ISSUE TITLE
Autofill gives wrong characters

### ISSUE THREAD

**Issue by stev-kast** [carnager/rofi-pass#221]
When I use Autofill and there are characters they are filled as I was using an English keyboard layout. My keyboard has a Latam layout and it fills the credentials incorrectly. For example on emails the "@" character is replaced for "2" and in passwords "?" is replaced by "_". I am not sure if my keyboard layout really matters but that is how I saw the problem

**Comment by moviuro** [comment]
https://github.com/carnager/rofi-pass#rofi-pass-prints-garbage-instead-of-my-actual-passes

**Comment by stev-kast** [comment]
Thanks, sorry for not reading further.
