### ISSUE TITLE
Rofi error prompt (`Rofi is unsure what to do`) with default config 

### ISSUE THREAD

**Issue by bitspook** [carnager/rofi-pass#226]
`rofi` version: 1.7.5
`rofi-pass` version: 1.5.3

On entering `rofi-pass` in terminal (or triggering it in any other way), rofi v1.7.5 shows this error prompt:

![rofi-2022-09-08-1509-00000](https://user-images.githubusercontent.com/1437091/189092791-84d8fac4-929a-4c3e-9880-7f7b4bf19dce.png)

Culprit seem to be https://github.com/carnager/rofi-pass/blob/master/rofi-pass#L843-L845

![image](https://user-images.githubusercontent.com/1437091/189093039-811359bb-b1d8-48d3-b26f-5d41d4fd39ea.png)

`rofi -dump-xresources` is no longer a valid option, and rofi throws a fit when it encounters that.

As a workaround, adding `help_color="#4872FF"` (i.e a non-empty `help_color`) in config don't cause this problem.

**Comment by Narrat** [comment]
Just creating the connection to https://github.com/carnager/rofi-pass/issues/223
