### ISSUE TITLE
Login not possible with last commit

### ISSUE THREAD

**Issue by tristelune1** [carnager/rofi-pass#3]
Hello, I had a problem with rofi-pass and to see if there is a fix, I have installed
the last version from git. Unfortunately, I can't login anymore. 

I do the following: Start rofi-pass, choose a login (I get the list of the possible logins) and hit "Enter". After that, nothing happens
I tried in a terminal and it's much more interesting:

```
% rofi-pass 
Error: 14 is not in the password store.
Error: 14 is not in the password store.
type: unrecognized option '--file'
Usage: type [--window windowid] [--delay milliseconds] <things to type>
--window <windowid>    - specify a window to send keys to
--delay <milliseconds> - delay between keystrokes
--clearmodifiers       - reset active modifiers (alt, etc) while typing
--args N  - how many arguments to expect in the exec command. This is
            useful for ending an exec and continuing with more xdotool
            commands
--terminator TERM - similar to --args, specifies a terminator that
                    marks the end of 'exec' arguments. This is useful
                    for continuing with more xdotool commands.
-h, --help             - show this help output
	type: unrecognized option '--file'
Usage: type [--window windowid] [--delay milliseconds] <things to type>
--window <windowid>    - specify a window to send keys to
--delay <milliseconds> - delay between keystrokes
--clearmodifiers       - reset active modifiers (alt, etc) while typing
--args N  - how many arguments to expect in the exec command. This is
            useful for ending an exec and continuing with more xdotool
            commands
--terminator TERM - similar to --args, specifies a terminator that
                    marks the end of 'exec' arguments. This is useful
                    for continuing with more xdotool commands.
-h, --help             - show this help output
```

I assume the problem is with xdotool. Could you try first on your system ? I have a Gentoo system
and it's possible something in missing in the package. But I have also an Archlinux system and it doesn't work. But I'm not sure that on Arch the git package install the last commit.

**Comment by tristelune1** [comment]
Sorry, I forgot, perhaps you know the problem, because you are doing
some modifications. In this case, could you tell me which version I can install ?

**Comment by carnager** [comment]
update rofi from git.

**Comment by tristelune1** [comment]
No, it still doesn't work. I have tested on my gentoo system. I have the same error message. I think the problem is with the argument '--type' for xdotool. Does it works for you ? If yes, perhaps the problem is with xdotool. I have the version 2.20110530.1 and there is a newer version (3.20150503.1). If it's the problem, I'll try to create the package for gentoo to see if it fixes the issue.

**Comment by carnager** [comment]
no, there is something fishy going on. can you show the output of `bash -x /path/to/rofi-pass`?
if you have the time, you can join #gmpc on freenode.

**Comment by tristelune1** [comment]
Tell me if it's easier to for you to you that I join #gmpc. In fact I don't use freenode but I notice it will be necessary in the future ;-). So first information, but it seems it changes nothing: my shell is zsh. But bash in installed, no problem. If I run the command you gave me, I get the following:

http://pastebin.fr/40705

Just one thing, perhaps something is missing in my package (gentoo) and that's the reason why it doesn't work:

 Content of rofi-pass:

    /etc
    /etc/rofi-pass.conf
    /usr
    /usr/bin
    /usr/bin/addpass
    /usr/bin/rofi-pass
    /usr/share
    /usr/share/doc
    /usr/share/doc/rofi-pass
    /usr/share/doc/rofi-pass/README.md.bz2
    /usr/share/doc/rofi-pass/config.example.bz2
    /usr/share/doc/rofi-pass/parsers
    /usr/share/doc/rofi-pass/parsers/chromium.bz2
    /usr/share/doc/rofi-pass/parsers/firefox.bz2`

**Comment by carnager** [comment]
something is very odd. every line is doubled in that outpost. that is not normal.

**Comment by tristelune1** [comment]
Not the command you gave me ? I still not see the difference :-(. 

Ok, now I understand: the problem has to do with rofi. I use the last version of rofi-pass, but rofi 0.15.7. So that's the problem. On Archlinux it works without a problem after reinstalling rofi-git. At the moment I have chosen for Gentoo to install the version of the commit "fcac25e8fb9f0111d00142b5cf61e471584480d5", it's the version of 22 th July. Perhaps on Gentoo I will create a rofi-git package. 

Now everything works as expected, thank you! I let you close this issue if everything is also alright for you!

Thank you!

**Comment by carnager** [comment]
you can install latest version of rofi-pass, like i explained. it will work now with rofi 0.15.7.
just set rofiopts="-no-levenshtein-sort" in config file
