### ISSUE TITLE
Setting '-font' option for rofi messes up interface

### ISSUE THREAD

**Issue by craftyguy** [carnager/rofi-pass#33]
If I include '-font "Monospace 10"' (or any font, for that matter) in rofiopts, the interface is unusable.

Here's the rofiopts config:
rofiopts='-i -font "Monospace 10" -no-levenshtein-sort'

%   rofi -version             
Version: 0.15.12

 %   rofi-pass --help
rofi-pass (Version: 1.2)

I would attach a screenshot, however rofi-pass intercepts all keyboard key presses and I'm unable to launch scrot :)

**Comment by craftyguy** [comment]
Setting font in ~/.Xresources seems to work correctly though.

.Xresources:
rofi.font:    Monospace 10

**Comment by carnager** [comment]
By the way. rofi can make screenshots of it's own window with Alt+Shift+s. Though it wouldn't have worked in this case. Still a handy feature.

**Comment by craftyguy** [comment]
Hmm, this fix actually breaks handling other options to rofi. For example, this doesn't behave as expected anymore:
 
    rofiopts="-i -m 0 -location 2 -no-levenshtein-sort"

Previously, the -location 2 would sent rofi to the top of the screen, but it seems to be ignored now.

**Comment by carnager** [comment]
ok, i played with this for quite a while and couldnt find a good and user friendly solution. So i got rid of the rofiopts option and instead exposed the _rofi function itself to config file.
