### ISSUE TITLE
Wrong special chars while typing first field

### ISSUE THREAD

**Issue by thomasba** [carnager/rofi-pass#34]
I tried autotype with only one filed, the password. In my case the password contains several special chars like `;` and `@`. They were typed as `<` and `q`.
However also a Username containing these chars gets messed up. In fact it's always the first field, that gets messed up.

The script itself gets the correct data, I create a test-password and executed `bash -x /usr/bin/rofi-pass`. The output:
- [rofi-pass-with-username](https://gist.github.com/thomasba/71f4420b95103f2e1adbb3de9dd7cf5e) (the password is typed correctly)
- [rofi-pass-without-username](https://gist.github.com/thomasba/e91f7aa86e937cef64a6d4601e76bc8e) (Typed password: ```<<><123q´`!%&``` should be: ```;<>;123@´`!%/```)

**Comment by thomasba** [comment]
Ok, it’s a bug in xdotool: http://stackoverflow.com/questions/17853287/xdotool-and-keyboard-layout

**Comment by carnager** [comment]
for reference, I reported this a while ago: https://github.com/jordansissel/xdotool/issues/97

**Comment by carnager** [comment]
@thomasba can you try latest commit and set keyboard="YOUR_LAYOUT"?

**Comment by carnager** [comment]
well, for now I will consider this fixed...
