### ISSUE TITLE
rofi-pass breaks with mawk

### ISSUE THREAD

**Issue by makkus** [carnager/rofi-pass#36]
This is not really an issue with rofi-pass, but I thought I'd mention it here, because it took me a while to figure out why the same rofi-pass worked perfectly on one machine, but not on another one. Seems like Ubuntu ships uses mawk instead of gawk as the default alternative for awk now (maybe I'm wrong, only got a sample size of one, point being mawk doesn't work), and that somehow breaks the line parsing in:

`       _id=$(echo -e "${LINE}" | awk -F ':[[:space:]]*' '{print $1}')`

Xdo-typing the password still works, but none of the other variables like user or url can be used. For example, autotype always omitts the user. Might be worth mentioning in the Readme that *gawk* is a requirement, not *awk*.

**Comment by carnager** [comment]
thanks for letting me know. Changed README.
