### ISSUE TITLE
Tagging releases?

### ISSUE THREAD

**Issue by hiberno** [carnager/rofi-pass#4]
Hey! First of all: let me thank you for developing rofi-pass, it's quite useful :) Do you think about tagging releases at some point? It would make for saner packaging (I am packaging this for NixOS) imho. Anyway, keep up the good work!

**Comment by carnager** [comment]
i am not sure... i tend to introduce config changes :smile:

**Comment by bastelfreak** [comment]
+1 for tags and semantic versioning. this would make packaging way easier.

**Comment by carnager** [comment]
https://github.com/carnager/rofi-pass/releases/tag/1.0

**Comment by hiberno** [comment]
Thanks! :)
