### ISSUE TITLE
Sorry rofi cannot understand the key combination: !Return

### ISSUE THREAD

**Issue by fogine** [carnager/rofi-pass#43]
> Sorry rofi cannot understand the key combination: !Return

On current master `rofi-pass` throws the error message and exits due to the API changes in `rofi` see https://github.com/DaveDavenport/rofi/issues/290 

The last `rofi-pass` release works tho.

**Comment by carnager** [comment]
change your config then?

**Comment by fogine** [comment]
Oh, I'm sorry, I totally forgot to mention details in a hurry. I edited the title, so it reflects actual error.
`!Return` sequence is used only at current master in `rofi-pass` bash script, not in previous releases.

**Comment by carnager** [comment]
well, yes. this needs the git version of rofi.

**Comment by fogine** [comment]
Ok, Just wanted to thank you for sharing your plugin. It's really helpful
