### ISSUE TITLE
Unsafe use of /tmp

### ISSUE THREAD

**Issue by justinsteven** [carnager/rofi-pass#45]
`rofi-pass` has unsafe use of /tmp

```
20:26:50[justin@diablo ~/opt/rofi-pass]% git show --oneline
b6dcf56 Merge pull request #44 from qbit/master

20:27:02[justin@diablo ~/opt/rofi-pass]% ag tmp
rofi-pass
36:    rm -f "/tmp/$USER-rofi-pass/last_used"
37:    echo "${root}: $selected_password" > "/tmp/$USER-rofi-pass/last_used"
48:    rm -f "/tmp/$USER-rofi-pass/last_used"
49:    echo "${root}: $selected_password" > "/tmp/$USER-rofi-pass/last_used"
500:# create tmp dir
501:if [[ ! -d /tmp/$USER-rofi-pass ]]; then
502:  mkdir "/tmp/$USER-rofi-pass"
520:if [[ -r "/tmp/$USER-rofi-pass/last_used" ]] && [[ $1 == "--last-used" || $1 == "--show-last" ]]; then
521:  export root; root=$(awk -F ': ' '{ print $1 }' "/tmp/$USER-rofi-pass/last_used")
546:      if [[ -r "/tmp/$USER-rofi-pass/last_used" ]]; then
547:        entry="$(awk -F ': ' '{ print $2 }' "/tmp/$USER-rofi-pass/last_used")"
552:      if [[ -r "/tmp/$USER-rofi-pass/last_used" ]]; then
553:        selected_password="$(awk -F ': ' '{ print $2 }' "/tmp/$USER-rofi-pass/last_used")" showEntry
```

This means that another user on the box, who can create a symlink at `/tmp/${VICTIM_USER}-rofi-pass` before `${VICTIM_USER}` uses rofi-pass, can cause `${VICTIM_USER}` to:

* `rm -f` a file called `last_used` in a directory of the attacker's choosing
* redirect the text that corresponds to `"${root}: $selected_password"` into a file called `last_used` in a directory of the attacker's choosing

An example of `nobody` being able to cause me (`justin`) to send some text to `~justin/.ssh/last_used`:

```
20:31:14[justin@diablo ~/opt/rofi-pass]% sudo -u nobody ln -s /home/justin/.ssh /tmp/justin-rofi-pass

20:31:36[justin@diablo ~/opt/rofi-pass]% ls -la /tmp/justin-rofi-pass
lrwxrwxrwx 1 nobody nogroup 17 Jul 16 20:31 /tmp/justin-rofi-pass -> /home/justin/.ssh

20:31:41[justin@diablo ~/opt/rofi-pass]% ls -la ~/.ssh/last_used
ls: cannot access '/home/justin/.ssh/last_used': No such file or directory

<use rofi-pass to access the pass password item called "demopassword">

20:32:14[justin@diablo ~/opt/rofi-pass]% ls -la ~/.ssh/last_used
-rw-r--r-- 1 justin justin 43 Jul 16 20:32 /home/justin/.ssh/last_used

20:32:38[justin@diablo ~/opt/rofi-pass]% cat ~/.ssh/last_used
/home/justin/.password-store: demopassword
```

It looks as though an attacker may be able to control the variables `${root}`, `${entry}` and `${selected_password}` depending on how the victim user launches rofi-pass. I haven't gone too far down that rabbit hole just yet.

`/tmp/` should be considered hostile and full of directories/files/symlinks planted by other users.

**Comment by carnager** [comment]
whats your suggestion. just fix permissions of the file?

**Comment by justinsteven** [comment]
> There is no real danger here. All an attacker can get is the filename of last used gpg file. He cannot decrypt it and not even access it.

An attacker can cause a victim user to `rm -f` a file named `last_used` at a location of their choosing via a planted symlink. I demonstrated that an attacker can cause the writing of some text that they don't control to to a file named `last_used` at a location of their choosing via a planted symlink.

It's not a privacy/confidentiality impact, but an availability/integrity one. It's a very small danger, but it's a danger.

The patch looks good, thanks!
