### ISSUE TITLE
freebsd grep

### ISSUE THREAD

**Issue by gregf** [carnager/rofi-pass#46]
BSD grep doesn't contain -P for perl regex. There is a package called gnugrep which installs gnugrep to /usr/local/bin/grep. It would be nice to have rofi detect if you are on freebsd and use the right grep.

**Comment by gregf** [comment]
readme should probably have a freebsd section stating that freebsd needs gnugrep and gawk installed. That being said rofi-pass git requires rofi-git which isn't really possible on freebsd at this time due to missing packages in the ports tree. Do you have any idea where things diverged from rofi-0.5.12?

**Comment by gregf** [comment]
rofi-git does compile qball helped me out with that. Now the problem is xdotool is missing the --file switch so that's probably out dated.

**Comment by carnager** [comment]
just checked ports, freebsd ships a version of xdotool from 2011... No comment.

**Comment by gregf** [comment]
Its actually only one version behind, that was the previous version. I sent in a patch to update the port. That being said FreeBSD was a bad experience. Everything down to getting fonts to work was a fight. I gave up back on arch. Closing this because I won't be working on it now.
