### ISSUE TITLE
Embed default config in rofi-pass

### ISSUE THREAD

**Issue by stonewareslord** [carnager/rofi-pass#48]
If neither config file exists, the program prints errors such as:

    The script command 'window' has 1 options, but needs 2: <name>:<script>.
    Invalid script switcher: window

And won't work overall. As soon as the default config is copied, rofi-pass works fine. I think that after the config files are sourced, default values should be loaded for unset variables. This would prevent confusing errors like the ones shown above.  One possible implementation could be to add config lines like this:

    USERNAME_field=${USERNAME_field:-'user'}
    AUTOTYPE_field=${AUTOTYPE_field:-'autotype'}
    ...

after sourcing both config files. This will set the fields to their default value only if they are unset. Though I'm not sure how the `_rofi` command would be implemented this way. Possibly use something like:

    declare -f  _rofi || _rofi() {
      rofi -z -i -width 700 -no-levenshtein-sort "$@"
    }

**Comment by carnager** [comment]
Oh I am suprised i havent embedded the defaults, I normally do. That said, I dont think all these checks are necessary. Simply set all variables. Then source global config. Then source local config, which will automatically overwrite values.

**Comment by carnager** [comment]
Made is this way now, since I am used to it from my other scripts. Thanks for the reminder!
