### ISSUE TITLE
config-file 

### ISSUE THREAD

**Issue by hiberno** [carnager/rofi-pass#5]
Is there any way to change the path to the config file? `rofi-pass` seems to expect it at `/etc/rofi-pass`, right? How can I tell `rofi-pass` that it is at `~/.rofi.conf` for example?

**Comment by carnager** [comment]
rofi-pass reads $HOME/.config/rofi-pass/config.

settings set in that file will overwrite global ones

**Comment by hiberno** [comment]
Thank you!
