### ISSUE TITLE
Autotyping with fewer keystrokes

### ISSUE THREAD

**Issue by pigmonkey** [carnager/rofi-pass#52]
My habit with previous versions of rofi-pass has been to find the entry I want and hit `enter` for rofi-pass to autotype it. With rofi-pass v1.4, hitting `enter` on the entry brings up the new menu asking me what I want to do. I have to hit `enter` a second time, or I have to hit `alt+1` when on the entry.

Personally I'm not a fan of the new menu asking me what I want to do as it requires an extra keystroke. I can see how it would be nice for new users, or for those who do not autotype the majority of the time. Is it possible to make the default entry behaviour configurable? It would be great if the default could remain the same, but I could configure the default action to be `autotype` instead of `menu` or something.

I actually see a `default_do` config option currently that kind of looks like what I am imaging, but it doesn't look like it is being used for anything.

**Comment by carnager** [comment]
That was pure accident, default_do was meant to work as expected. does now.

**Comment by carnager** [comment]
Also released a bugfix release 1.4.1 with both your found issues fixed

**Comment by pigmonkey** [comment]
Thanks! Setting `default_do='autotype'` in my config gets me the desired behaviour with the latest release.

`autotype` is not included in the comment that lists the options for `default_do` in the default config. It probably isn't worth cutting a new release just for that.

```
default_do='menu' # menu, copyPass, typeUser, typePass, copyUser, copyUrl, viewEntry, typeMenu, actionMenu, copyMenu, openUrl
```

**Comment by carnager** [comment]
It does? thats strange, because the correct value is "autopass" :)

**Comment by pigmonkey** [comment]
I changed my config to `autopass` to be more correct.

**Comment by carnager** [comment]
as noticed in other report. i am getting strange errors in output, which i dont get with autotype as option. spent half the night debugging this and cant find out why this happens. so maybe i should just change the default to autotype, like you suggested and finally be done with these 2 reports :)
