### ISSUE TITLE
Passwords ending in a colon (':') are listed as items.

### ISSUE THREAD

**Issue by Tmplt** [carnager/rofi-pass#54]
Creating a `pass` entry with a password ending in a ':' makes it show up as an item in `rofi-pass`:

```
$ pass insert test
Enter password for test: testpw:
Retype password for test: testpw:
$ rofi-pass
```
![rofi-pass screenshot](https://ptpb.pw/23Uc)

**Comment by carnager** [comment]
can you test?

**Comment by Tmplt** [comment]
That change fixed it.
