### ISSUE TITLE
Copied passwords do not end up in clipboard with CopyQ

### ISSUE THREAD

**Issue by Brottweiler** [carnager/rofi-pass#55]
I am using [CopyQ](https://hluk.github.io/CopyQ/) as my clipboard manager, and when I start `rofi-pass`, then select an entry, then <kbd>ALT+p</kbd>, it copies it... Just that in CopyQ, there's no new copied item... 

However, after 45 seconds when the clipboard is cleared, a new item ends up in CopyQ that seems to be two empty lines that are copied.

**Comment by carnager** [comment]
what clipboard did you set in config?

**Comment by Brottweiler** [comment]
```cfg
# Clipboard settings
# Possible options: primary, clipboard, both
clip=primary
```

I've tried change `primary` to any of those with the same result.

**Comment by rhssk** [comment]
Had the same issue but then realized I had copied `/etc/rofi-pass.conf` 1:1 to `~/.config/rofi-pass` while it is required to rename it to `config`. After that and changing `clip` from `primary` to `clipboard` everything works.

**Comment by Brottweiler** [comment]
@rhssk I hoped for this to be the case, but I just checked now, and the filename is `~/.config/rofi-pass/config` 😞

**Comment by rhssk** [comment]
Can you put your config contents here? Also, after entering this `echo -n "test" | xclip -selection clipboard` in terminal can you paste the copied text ("test")?

**Comment by Brottweiler** [comment]
Yep, that command works.

```cfg
# permanently set alternative root dir
# root=/path/to/root

# rofi command. Make sure to have "$@" as last argument
_rofi () {
    rofi -i -width 700 -no-levenshtein-sort "$@"
}

# keyboard layout (set this to your actual layout. E.g. keyboard="de us"
#keyboard=us

# fields to be used
URL_field='url'
USERNAME_field='user'
AUTOTYPE_field='autotype'

# delay to be used for :delay keyword
delay=2

## Programs to be used
# Editor
EDITOR='gvim -f'

# Browser
BROWSER='google-chrome-beta'

## Misc settings

default_do='menu' # menu, autotype, copyPass, typeUser, typePass, copyUser, copyUrl, viewEntry, typeMenu, actionMenu, copyMenu, openUrl
auto_enter='false'
notify='false'

# color of the help messages
# leave empty for autodetection
help_color="#4872FF"

# Clipboard settings
# Possible options: primary, clipboard, both
clip=clipboard

# Options for generating new password entries
default_user=Brottweiler
default_user2=Brott
password_length=24

# Custom Keybindings
autotype="Alt+1"
type_user="Alt+2"
type_pass="Alt+3"
open_url="Alt+4"
copy_name="Alt+u"
copy_url="Alt+l"
copy_pass="Alt+p"
show="Alt+o"
copy_entry="Alt+2"
type_entry="Alt+1"
copy_menu="Alt+c"
action_menu="Alt+a"
type_menu="Alt+t"
help="Alt+h"
switch="Alt+x"
insert_pass="Alt+n"
```

**Comment by rhssk** [comment]
Can you even get the unlocked password with rofi-pass? Try selecting record, hit Enter and choose `pass`. Does it print anything relevant at all?

**Comment by Brottweiler** [comment]
@rhssk Now when you say it, I don't even get anything regarding unlocking with gpg key... Surely I'd need to type my passphrase somewhere?

If I click Enter to choose an entry, then Enter on `pass`, nothing happens.

**Comment by rhssk** [comment]
Yes, you should get some kind of dialog menu asking for your GPG passphrase. Does running plain `pass` with any password record from terminal work for you?

**Comment by Brottweiler** [comment]
Plain `pass` shows me all my different websites and accounts. Obviously, `pass somesite.com/account` gives me the pinentry to write password (for me, `pinentry-curses`, not a GUI one). After I've typed my passphrase in, terminal shows me my password. And then ofcource I can use `-c` to copy it to clipboard.

**Comment by rhssk** [comment]
I assume you're on Ubuntu so I'm not familiar with their packages, but you should make sure that you have the GUI one available as pinentry-curses would obviously need a terminal called first (I doubt rofi-pass can do that for you). I just checked and there seem to be some GUI packages available. Try playing around with `pinentry-qt` and `pinentry-gnome3` or `pinentry-gtk2`.

**Comment by Brottweiler** [comment]
Not sure why you think I am on ubuntu, but I am on arch 😛 

Hmm, I edited my `gpg-agent.conf` file to use the `qt` one instead of `curses`, but I also assume I had to restart gpg-agent. I used `killall` for it, but not sure how to start it, so I just rebooted to let it start. pass gives me `gpg: decryption failed: No secret key`, so I need to solve that first...

**Comment by rhssk** [comment]
Couldn't find `pinentry-curses` in Arch repos but could in Ubuntu's. Turns out it is build in `core/pinetry`. You can just kill gpg-agent and it will be called when needed. I don't have anything configured in `gpg-agent.conf` besides `default-cache-ttl`, mostly default behavior. Check this section out: https://wiki.archlinux.org/index.php/GnuPG#pinentry

**Comment by Brottweiler** [comment]
I fixed my issue. For reference, I think using `killall gpg-agent` is bad. From reading `man gpg-agent`, I killed gpg agent with `gpgconf --kill gpg-agent`, then started it with `gpgconf --kill gpg-agent`, and now it works.

@rhssk 

```sh
% ls -l /usr/bin/pinentry*
lrwxrwxrwx 1 root root     14 Nov 27 18:54 /usr/bin/pinentry -> pinentry-gtk-2
-rwxr-xr-x 1 root root  64976 Nov 27 18:54 /usr/bin/pinentry-curses
-rwxr-xr-x 1 root root  52400 Nov 27 18:54 /usr/bin/pinentry-emacs
-rwxr-xr-x 1 root root  73488 Nov 27 18:54 /usr/bin/pinentry-gnome3
-rwxr-xr-x 1 root root  82160 Nov 27 18:54 /usr/bin/pinentry-gtk-2
-rwxr-xr-x 1 root root 115328 Nov 27 18:54 /usr/bin/pinentry-qt
-rwxr-xr-x 1 root root  56560 Nov 27 18:54 /usr/bin/pinentry-tty
```

So because I now use the `qt` one, and already tried it out in terminal, I already identified. So now when I copy entries in rofi-pass, it works. So the issue was pinentry being curses and not a GUI one. Closing, thanks for the help.

**Comment by rhssk** [comment]
Cheers

**Comment by carnager** [comment]
I should probably add this to the README

**Comment by Brottweiler** [comment]
Since it's unrelated to the clipboard manager, I edited the title of this issue to reflect what the issue actually was; that the password didn't get copied, and that pinentry didn't show up at all.

**Comment by Brottweiler** [comment]
@carnager Do you think it would be possible, if having the `curses` pinentry enabled, to spawn a terminal? So instead of using the gtk one, and having a GUI pop up, you get a terminal to popup, with `pinentry-curses`. After entering the password successfully, it closes.

**Comment by carnager** [comment]
It's not rofi-pass that spawns anything. it isn't even pass itself. it's gnupg that calls the helper.

**Comment by rhssk** [comment]
You could specify pinentry program in you `~/.gnupg/gpg-agent.conf` like this:
`pinentry-program termite --exec="/usr/bin/pinentry-curses"`
or if you're using urxvt
`pinentry-program urxvt -e "/usr/bin/pinentry-curses"`

**Comment by Brottweiler** [comment]
True, but then the issue is when I actually use the terminal to use `pass`, it will still launch a new terminal. First world problems...

**Comment by carnager** [comment]
You could do something like this: http://unix.stackexchange.com/questions/236746/change-pinentry-program-temporarily-with-gpg-agent

**Comment by Brottweiler** [comment]
I'm trying to get the above script work with rofi-pass but I'm not being successfull. I've tried simply just copy pasting the script to the config, but all I get is the `OK Pleased to meet you` message which you get if you try to run the `pinentry-gtk-2` for example by itself. 

Any idea?

**Comment by xyakimo1** [comment]
I had a similar problem: when executing rofi-pass with an i3 key binding, pinentry didn't show up, but if I ran rofi-pass from a terminal emulator, everything worked fine and pinentry-curses was used. Installing the qt-based pinentry helped (`sudo dnf install pinentry-qt` on Fedora).

**Comment by xyakimo1** [comment]
Does anybody have an idea on how to make pinentry-curses work?
