### ISSUE TITLE
Username/password is entered incorrectly in Steam

### ISSUE THREAD

**Issue by poisonby** [carnager/rofi-pass#56]
Example pass information:
```
John123
---
user: John
```

When I press autotype into Steam, this happens:
![Steam](https://ptpb.pw/AXpq)

Part of the password is inserted into the account name field.

**Comment by carnager** [comment]
Something happened in latest steam UI.
Add this to your file:

```
autotpye: user :tab :tab pass
```

**Comment by poisonby** [comment]
That seems to have fixed it, thanks!
