### ISSUE TITLE
Autoselection when the mouse is over the rofi window

### ISSUE THREAD

**Issue by antoyo** [carnager/rofi-pass#57]
Hello.
When the mouse is over the rofi (pass) window when it starts, a password is automatically selected.
It should not autoselect a password.
rofi run does not have this issue, so I believe the issue is in the options sent to rofi.
Thanks to fix this issue.

**Comment by carnager** [comment]
I don't even understand what you just said :)
Can you elaborate?

**Comment by carnager** [comment]
Sounds to me like you have -auto-select in your rofi settings (~/.Xresources or ~/.config/rofi/config) and only have one password entry.

**Comment by antoyo** [comment]
No, I don't have this option and I have more than one password entry.
I tried adding the option `rofi.auto-select: false`, but I still get this issue.
Is there any debug mode for `rofi`/`rofi-pass` so that I can see what happen?

**Comment by carnager** [comment]
bash -x /path/to/rofi-pass

**Comment by antoyo** [comment]
[I attached the logs to this post.](https://github.com/carnager/rofi-pass/files/539914/log.txt)

I don't know why I get:
```
+ selected_password=path/to/password
```
since I did not select a password (it is automatically selected).
Could it be caused by the `-select ''` option?
Do you see something suspicious in this log?
Thanks for your help.

**Comment by carnager** [comment]
easy to test: run `echo -e "1\n2\n" | rofi -dmenu -select ''`

**Comment by antoyo** [comment]
I tested with your command and it does not seem to be caused by `-select ''`.
Do you have any idea by looking at the logs file?
Thanks for your help.

**Comment by carnager** [comment]
that log seems perfectly fine. and in fact your log claims a return code of "0", which in theory can only be caused by hitting Enter

**Comment by carnager** [comment]
which rofi version?

**Comment by antoyo** [comment]
```
~ rofi -v
Version: 1.2.0
```

**Comment by carnager** [comment]
how exactly are you starting rofi-pass?

**Comment by antoyo** [comment]
With `rofi`, but the same issue arise when I start it from the terminal.

**Comment by carnager** [comment]
well i am clueless. there is no way rofi-pass can trigger this and your rofi options themselves dont trigger it either.

**Comment by roomcays** [comment]
Well, I must report, that I have just faced this issue too. My instance of `rofi-pass` behaves exactly like @antoyo described.
At the same time `rofi` by itself does not bother whether mouse cursor is *above* it's window or not...

**Comment by carnager** [comment]
To the original poster:

```
echo -e "1\n2\n3" | rofi -i -width 700 -no-levenshtein-sort -mesg 'Welcome to rofi-pass. Use <span color='\''#ffffff'\''>Alt+n</span> to create a new pass entry.
Run menu with <span color='\''#ffffff'\''>Enter</span>. For more help hit <span color='\''#ffffff'\''>Alt+h</span>.' -dmenu -kb-accept-entry '!Return' -kb-custom-1 Alt+1 -kb-custom-2 Alt+2 -kb-custom-3 Alt+3 -kb-custom-4 Alt+4 -kb-custom-5 Alt+u -kb-custom-6 Alt+p -kb-custom-7 Alt+o -kb-custom-8 Alt+l -kb-custom-9 Alt+t -kb-custom-14 Alt+a -kb-custom-15 Alt+c -kb-custom-16 Alt+h -kb-custom-17 Alt+x -kb-custom-18 Alt+n -dmenu -select '' -p 'rofi-pass > '
```

This is the *exact* command being run. Run it manually. Same thing happening?

**Comment by pigmonkey** [comment]
I've occasionally experienced this as well. My cursor is rarely ever in the middle of the screen, so it happens infrequently.

Here is a screencast (taken with teiler!) of the behaviour: http://files.pig-monkey.com/rofibug.mp4

You can see my cursor is in the middle of the screen. I paste the command above and hit enter. Because my cursor is immediately above the `1` entry, it is automatically selected.

Then I move my cursor to the upper left, paste the command, and hit enter. As expected, nothing happens until I manually hit `3<enter>`.

**Comment by carnager** [comment]
I wonder what triggers this. can you try to ommit `-kb-accept-entry '!Return'` argument from the command?

**Comment by pigmonkey** [comment]
I cannot get it to trip when I remove that. If I keep my cursor in the same spot and put `-kb-accept-entry '!Return'` back in, it autoselects like in the screencast. So, yeah, seems to be that.

**Comment by carnager** [comment]
pffft. I explicitly asked for the result of the command without -kb-accept-entry in my 3rd post on oct. 19th. It was ignored.

**Comment by antoyo** [comment]
Could you please release a new version with this fix so that we can update the package in distribution repositories?
Thanks a lot.

**Comment by carnager** [comment]
Was waiting for comfirmation that this fixes things.

**Comment by antoyo** [comment]
I cannot reproduce the issue with this fix.
Thanks.

**Comment by antoyo** [comment]
This issue happens with the new release of 2 days ago.

**Comment by carnager** [comment]
Make sure you have the above mentiond rofi option in your _rofi config.

From release notes:
`Remove hardcoded rofi options from code. That's what the _rofi function in config file is for.`
