### ISSUE TITLE
again: sorry, cannot understand key combination: !Return

### ISSUE THREAD

**Issue by RichardMore** [carnager/rofi-pass#58]
After (installing all required apps) `git clone` or `sudo make install` only thing that I get when running `rofi-pass` **is sorry, cannot understand key combination: !Return**. Is this still the #43 issue or is it just me who cannot integrate it into rofi?
And can you provide a sample code about how to use it together with rofi? I am new to it...

**Comment by Narrat** [comment]
Without any information on the versions you installed, every answer is a guess.

**Comment by carnager** [comment]
This sounds like outdated rofi version. IIRC this was added in rofi 1.1

**Comment by RichardMore** [comment]
I installed with `apt-get install rofi` under Ubuntu, local build failed, Rofi version is 0.15.7.
rofi-pass won't work on its own either.

**Comment by Narrat** [comment]
It's issue #43
Manually install a more recent version or look for a PPA which offers a more recent version (dunno if there is one)

**Comment by RichardMore** [comment]
Thank you, finally with manually installing dependencies I could install rofi 1.2.0, with that I can run rofi-pass, but seem to have difficulties starting rofi-pass with rofi, can you write an example startup command for that?

**Comment by carnager** [comment]
you simply run "rofi-pass"?

**Comment by RichardMore** [comment]
Ohhh it my bad. I tried to run it like it was a previous rofi version: `rofi -modi "window,run,ssh,rofi-pass:rofi-pass" -s -key-run F12 -key-rofi-pass F10`
But now I realized that running a rofi deamon is not just not recommended, but impossible.

Thank you again for the help!

**Comment by carnager** [comment]
rofi-pass is a dmenu script, which is something different from a rofi modi-script. less integrated, but more features.

**Comment by RichardMore** [comment]
Yes, I start rofi-pass with `rofi-pass` command, with xbindkeys. Thanks for the help!
