### ISSUE TITLE
Leading whitespace in usernames

### ISSUE THREAD

**Issue by pigmonkey** [carnager/rofi-pass#6]
I have pass entries that look like this:

```
mysecretpassword
---
login:    username
url:      https://example.org
```

(Those are 4 spaces between `login:` and `username`.)

My rofi-pass config looks like this:

```
URL_field='url'
USERNAME_field='login'
```

When I use rofi-pass to type or copy the username, the result always has a leading white space character. It looks like rofi-pass is just splitting the line at `: ` (I think GitHub is stripping white space, but that is supposed to be a colon followed by a whitespace character).

I would like rofi-pass to strip leading and trailing whitespace from whatever field it is operating on. This could be done sed.

```
$ echo "   test   " | sed -e 's/^[ \t]*//' -e 's/[ \t]*$//'
test
```

**Comment by carnager** [comment]
can you try latest git?

**Comment by pigmonkey** [comment]
Fixed! Thanks.

**Comment by carnager** [comment]
there was a nasty bug with that commit. colons in fields would be cut off. hopefully fixed now

**Comment by carnager** [comment]
apparently it's not. need to look into this
