### ISSUE TITLE
cannot paste @ sign from pass entry

### ISSUE THREAD

**Issue by RichardMore** [carnager/rofi-pass#60]
When a pass entry contains an **@ sign**, rofi-pass cannot paste it into context, gives an **ˇ sign** instead. ($ sign does not work either, % does)

**Comment by carnager** [comment]
works for me. did you set the keyboard layout in config?

**Comment by RichardMore** [comment]
After setting the config to `keyboard="hu"`, only \\\@ works, but not always, I'd say rarely.

**Comment by carnager** [comment]
well. there is nothing I can do. This is the way xdotool works :(
see https://github.com/jordansissel/xdotool/issues/97

**Comment by RichardMore** [comment]
When using `keyboard="de us"` the @ problem seems to disappear, but since my keyboard is a hungarian one, `keyboard=hu` should be the optimal.
But maybe if it is possible, can it be than that before the app exits, it sets the keyboard to an other, like a secondary language?
Eg. `keyboard="de us"`, `secondary_keyboard="hu"` and before exit `setxkbmap ${secondary_keyboard}`
Opinion?

**Comment by RichardMore** [comment]
It seems to work now on Ubuntu 16.04 with all the latest utils, closing issue.
