### ISSUE TITLE
Not working when called from Linux Mint shortcuts launcher

### ISSUE THREAD

**Issue by Iambecomeroot** [carnager/rofi-pass#61]
I created a shortcut to launch the script using Linux Mint's keyboard settings. When I use the shortcut, the only option that shows up is pass even though my passwords also have user and autotype, and when I hit enter, nothing happens. When I call the script from the command line, everything is perfect. As a temporary workaround, I have changed the command to this: `gnome-terminal -e "rofi-pass"`. That works, but I have to click back to firefox or the password just goes into the terminal. 

Btw I use this script on my arch+xfce laptop and it's so nice. Thanks a bunch!

`uname -a`:

    Linux Zeus 3.19.0-21-generic #21~14.04.1-Ubuntu SMP Sun Jun 14 18:45:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

`pass version`:

    |-----------------------|
    |   Password Store      |
    |       v.1.4.2         |
    |       by zx2c4        |
    |                       |
    |    Jason@zx2c4.com    |
    |  Jason A. Donenfeld   |
    |-----------------------|

`sed --version`:

    sed (GNU sed) 4.2.2

`rofi -v`:

    Version: 0.15.11

`xdotool -v`:

    xdotool version 3.20140217.1

`gawk -V`:

    GNU Awk 4.0.1

`bash --version`:

     GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)
     Copyright (C) 2013 Free Software Foundation, Inc.
     License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
     
     This is free software; you are free to change and redistribute it.
     There is NO WARRANTY, to the extent permitted by law.

**Comment by carnager** [comment]
That sounds like missing enironment. I guess you use some kind of login manager?

**Comment by Iambecomeroot** [comment]
Yep. Whatever the default is for Linux Mint 17. I think it's mdm.

**Comment by carnager** [comment]
by the way, that rofi version is ANCIENT. I am surprised rofi-pass works at all :)

**Comment by Iambecomeroot** [comment]
I know. I had a hard time installing it at all. Trying to get off Mint as soon as possible.

**Comment by Iambecomeroot** [comment]
I broke Linux Mint trying to upgrade pass. On arch now. Everything working perfectly. About time.

**Comment by asymmetric** [comment]
I have the same problem when running `pass-rofi` from my `i3/config` file:

```
bindsym $mod+p exec /home/asymmetric/code/rofi-pass/rofi-pass
```

Running from the terminal works correctly instead.

What kind of environment is missing?
