### ISSUE TITLE
Default configuration is not usable with a non-US keyboard

### ISSUE THREAD

**Issue by moviuro** [carnager/rofi-pass#63]
Hi,

Consider the following:

```
% pass someaccount
supersecret
---
user: azerty123456
```

rofi-pass will print `qwerty!@#$%^` as username instead of `azerty123456`.

`xdotool` seems to be the criminal here, but everything just went downhill. (https://github.com/carnager/rofi-pass/blob/273b4d1eca1a46f56027d4191aad47f70020f036/rofi-pass#L117)

rofi-pass is unusable as is :sob: 

```
% localectl 
   System Locale: LANG=en_US.utf-8
                  LC_TIME=en_DK.utf-8
                  LC_MONETARY=fr_FR.utf-8
                  LC_NAME=fr_FR.utf-8
                  LC_ADDRESS=fr_FR.utf-8
                  LC_TELEPHONE=fr_FR.utf-8
                  LC_MEASUREMENT=fr_FR.utf-8
       VC Keymap: fr-pc
      X11 Layout: fr
```

**Comment by Narrat** [comment]
Did you specify your layout in the config?

**Comment by moviuro** [comment]
Ah, I must have jumped some steps. :fearful: 

1. I had no config file nor any idea there was one
2. `keyboard=fr` makes it work correctly, yay! :smile: 
3. I suggest changing the default value of the config file to some command output (`localectl(1)` or some proper agnostic commands like `setxkbmap -query | grep layout | grep -oE '[^: ]+$'`)

Thoughts?
