### ISSUE TITLE
Problem with Firefox and Roundcube

### ISSUE THREAD

**Issue by aminb** [carnager/rofi-pass#65]
Scenario: Open a Roundcube login page in Firefox and focus the username field.

Problem: Upon selecting a password from list of passwords and pressing enter, the focus in Roundcube login page is moved from the username to the password field.

This happens right before selecting a field for rofi-pass to type out.

**Comment by carnager** [comment]
known bug. use Alt+1 for roundcube in firefox.

**Comment by aminb** [comment]
I see. Thanks!

I also just noticed pressing <kbd>Ctrl-j</kbd> or <kbd>Ctrl-m</kbd> instead of <kbd>Enter</kbd> also works fine.

**Comment by carnager** [comment]
see updated comment. I added the !Return argument to default config in master
