### ISSUE TITLE
Disable keyboard repeat?

### ISSUE THREAD

**Issue by fd0** [carnager/rofi-pass#67]
Hi,

thanks a lot for writing rofi-pass! I have an issue with auto-typing passwords via xdotool: In about one third of the cases it types the password or username incorrectly because one character is typed twice. I suspected that this has something to do with keyboard repeat (I have a high repeat rate with a rather short delay, `xset r rate 180 60`). I added a bit of code to rofi-pass which disables keyboard repeat, types the password with xdotool, and the re-enables keyboard repeat (if it was enabled before). This solves my issue perfectly.

Would you be willing to accept a PR which adds this (and enables it by default)?

**Comment by carnager** [comment]
If the code works in all use cases (e.g. users setting different speeds or none at all) I would happily accept it.

**Comment by fd0** [comment]
I've added my code in PR #68. It doesn't touch repeat rate settings at all, but rather checks what the current state of repeat is (on or off), disables it, and after autopass is done sets the old state again.

**Comment by carnager** [comment]
seems fine to me. thanks

**Comment by carnager** [comment]
Could you add those checks for typing of single fields too?

**Comment by fd0** [comment]
Sure, see #69

**Comment by carnager** [comment]
thanks
