### ISSUE TITLE
Add xclip selection to config

### ISSUE THREAD

**Issue by pigmonkey** [carnager/rofi-pass#7]
Currently it appears that rofi-pass [copies usernames to the default selection](https://github.com/carnager/rofi-pass/blob/master/rofi-pass#L93) and passwords to both the [default](https://github.com/carnager/rofi-pass/blob/master/rofi-pass#L98) and [clipboard](https://github.com/carnager/rofi-pass/blob/master/rofi-pass#L99) selections. This was not intuitive to me -- I had to read through the script to see why usernames were not added to my clipboard after I copied them with rofi-pass.

I'm not sure if there is a reason for the difference in behaviour between copying usernames and passwords, but I think it would be nice to have the selection configurable by the user. Something like an `xclip_selection` setting in the configuration file, with possible options of `primary`, `secondary` and `clipboard`. I would then expect rofi-pass to apply this to both usernames and passwords.

**Comment by carnager** [comment]
there is no reason for it. sounds like a good idea

**Comment by carnager** [comment]
feature added in 4f1d2900d5695185de65c5826b8b18007dffef0b
Add `clip=primary` or `clip=clipboard` to your config

**Comment by pigmonkey** [comment]
Works. Thanks again!
