### ISSUE TITLE
combining bookmark mode and autofill?

### ISSUE THREAD

**Issue by 2Belette** [carnager/rofi-pass#70]
Hi,

I was using pass & passff firefox extention for quite a long time but after some recent security potential issues I prefer the approach of rofi-pass!
I am playing around and make it almost work like my old configuration, the only thing I am not able to do is to open the url automatically and autofill, is there a way to do that?

Bookmark mode is working correctly and opening a tab in my iceweasel and goes to the right link
Autofill is also working correctly (I noticed a little glitch where I need to click into a form box for the mouse to focus on it, if I don't do that before rofi-pass is not able to fill the form, I am sure there is a little tips for that?)

My idea would be to combine both

many thanks

**Comment by carnager** [comment]
This is not possible outside of the browser.

**Comment by 2Belette** [comment]
I agree with you but unfortunately a lot are not well designed...
Regarding a way to open the url + autofill so there is no way? It requires two steps in rofi-pass if I understand well? (one with bookmark to open the url and going back again to rofi-pass to autofill)
just to be sure I don't miss anything

many thanks again

**Comment by carnager** [comment]
There is no way to detect the username field outside of the browser. I could think of hacks to do it, but those would be unreliable and in worst case even a huge security flaw.
