### ISSUE TITLE
Confusing output when there is exactly one password in the `pass` database

### ISSUE THREAD

**Issue by taktoa** [carnager/rofi-pass#73]
See the title.

**Comment by carnager** [comment]
Actually I have no clue what you mean :)
A bit of effort when reporting issues is very welcome.

**Comment by taktoa** [comment]
I later figured out that the issue happens when `rofi.auto-select: true` is in the rofi config and there is exactly one password in the pass database. In general it might be a good idea to disable auto-select when using rofi-pass.

**Comment by carnager** [comment]
ah yes. i will add that. thanks.
