### ISSUE TITLE
Default autotype options?

### ISSUE THREAD

**Issue by Iambecomeroot** [carnager/rofi-pass#74]
Many of my password files have the same two bottom lines:
```
user: my@email
autotype: user :tab pass :enter
```
Is there a way to make this the default? I see the addpass command can add these to the files if you use it to generate the password but I want autotype to default to typing my email then the password event if the password file only has one line: the password.

**Comment by carnager** [comment]
@Iambecomeroot can you test 3f2524e273e2fbbc40c8f2b168cf99c49a41768d

**Comment by Iambecomeroot** [comment]
Perfect. Thank you!

**Comment by carnager** [comment]
ok, i think latest master has most issues sorted out. This change + some default options made the code even less complex, which is nice :)
