### ISSUE TITLE
Sort password entries in list

### ISSUE THREAD

**Issue by alexzeitgeist** [carnager/rofi-pass#75]
It's a tiny modification, but IMHO it makes a big difference.

    diff --git a/rofi-pass b/rofi-pass
    index 9e89493..970dfa0 100755
    --- a/rofi-pass
    +++ b/rofi-pass
    @@ -51,7 +51,7 @@ umask 077
     list_passwords() {
       cd "${root}" || exit
     
    -  find -L . -iname '*.gpg' -printf '%P\n' | \
    +  find -L . -iname '*.gpg' -printf '%P\n' | sort | \
         while read filename; do
           echo "${filename%.gpg}"
       done

**Comment by carnager** [comment]
I guess this should be sort -n, otherwise lowercase entries will be at the bottom

**Comment by alexzeitgeist** [comment]
Very true. Didn't notice because I use lowercase entries exclusively. ;p
