### ISSUE TITLE
Tab doesn't select the next entry

### ISSUE THREAD

**Issue by dkasak** [carnager/rofi-pass#78]
Pressing tab no longer selects the next entry in rofi-pass. The issue seems to have been introduced in 01eeb3e09ec1211254791aa65c635a5f30de46c7. I'm not sure why `-kb-row-tab` is being set to `''`. Is this deliberate? Removing this makes it work again.

**Comment by carnager** [comment]
it indeed was added on purpose since this fixes issues with latest rofi (git). I will move this part to the default _rofi function instead so it's easily editable

**Comment by carnager** [comment]
4e06cdf5836bd26012169dffe61361ff09ea7b08

**Comment by dkasak** [comment]
Thanks! What is the issue that it fixes, though?

**Comment by carnager** [comment]
rofi changed the way hotkeys are used, basically a whole new backened for it.

**Comment by dkasak** [comment]
My question was more along the lines of: what kind of breakage can I expect if I remove `-kb-row-tab ''` so that tab works again?

**Comment by carnager** [comment]
Ideally nothing happens. :)
