### ISSUE TITLE
Copy URLs

### ISSUE THREAD

**Issue by pigmonkey** [carnager/rofi-pass#8]
I frequently want to copy the URL from a pass entry, either to paste it into a specific browser window or to paste it into a different program. This is usually more useful to me than the ability to open the URL in the default browser directly from the entry. Could this be added to rofi-pass? Perhaps with a default mapping of `Alt+L` (l for link, since u is taken).

**Comment by carnager** [comment]
hmm, opening urls from main menu is already possible. to copy any kind of field to clipboard you can use the show menu. (default mapping: ctrl+return)

**Comment by pigmonkey** [comment]
I frequently have multiple browsers open (Firefox and Chromium), and multiple windows for each. I care about where the URL is opened -- both which browser and which window -- so using the "Open URL" option from the menu is generally not all that useful to me. I want more control than just specifying the default browser in the config and having the entries always open in that.

I'd also rather not open the entry to copy the URL. That exposes the password on the screen, and at that point I feel like it requires enough keystrokes that I may as well have just jumped over to a terminal and copied the URL from there. I have a shell alias that I use to get the URLs when I'm using pass directly, without a helper like rofi-pass

```
$ alias cpurl
cpurl='sed -n "/^url/Is/url:\s\+//p" | xsel -ib'
$ pass gmail | cpurl
```

But I'm really digging rofi-pass and I'd like to use it for all my pass interaction. The most convenient option for me would definitely be the ability to locate the entry with rofi-pass and then just hit `Alt+L`, or a similar keystroke.

**Comment by carnager** [comment]
i added a copy_url option in git.

**Comment by pigmonkey** [comment]
Perfect! A default mapping needs to be added to config.example. Otherwise, this works great.
