### ISSUE TITLE
List pwgen as a requirement

### ISSUE THREAD

**Issue by AlexDaniel** [carnager/rofi-pass#81]
Just tried generating a password and it did nothing. Obviously, ``pwgen`` was not installed.

I think [requirements](https://github.com/carnager/rofi-pass#requirements) section should list ``pwgen``. Feel free to note that it is only required if one wants to generate passwords.

**Comment by AlexDaniel** [comment]
Actually, this is my mistake. This has nothing to do with rofi-pass. Sorry :)

**Comment by carnager** [comment]
Hmm? This is a perfectly valid complaint. I will update the README

**Comment by Narrat** [comment]
Is there no chance to use the pw generation of pass itself? Sadly not a drop-in replacement as it behaves differently.

**Comment by AlexDaniel** [comment]
``pwgen`` is a dependency of ``pass`` itself.

**Comment by AlexDaniel** [comment]
Actually… ``rofi-pass`` [does indeed use ``pwgen``](https://github.com/carnager/rofi-pass/blob/ea5aaa1d4fb2dc0358ea8ada2385977cea30ccc7/rofi-pass#L581). I think I was confused by [``generatePass`` function](https://github.com/carnager/rofi-pass/blob/ea5aaa1d4fb2dc0358ea8ada2385977cea30ccc7/rofi-pass#L229-L231).

**Comment by Narrat** [comment]
With 1.7 pass dropped pwgen as dependency. Therefore the need to mention it in the Readme

**Comment by carnager** [comment]
> pwgen is a dependency of pass itself.

```
carnager@caprica ~ > grep pwgen /usr/bin/pass
carnager@caprica ~ >
carnager@caprica ~ > pacman -Qi pass | grep pwgen
carnager@caprica ~ > 
```

**Comment by carnager** [comment]
> Actually… rofi-pass does indeed use pwgen. I think I was confused by generatePass function.

That's a good point. It seems a bit messy to rely on both pass and pwgen for password creation in different places.
