### ISSUE TITLE
Menu header becomes redundant after a while

### ISSUE THREAD

**Issue by Rahtgaz** [carnager/rofi-pass#83]
It would be nice if the menu header could be enabled or disabled in the configuration. After a while it becomes unnecessary, and sticks like a sore thumb with the rest of the menus we created for rofi.

**Comment by carnager** [comment]
Yeah, I agree, the message seems rather nice at first but then seems out of place. i guess --help with all needed keys should be enough plus the alt+h hotkey which is there already.

**Comment by rotsix** [comment]
see my PR GH-01

**Comment by carnager** [comment]
Thanks a lot. But duplicating the whole set of arguments seems wrong (and i think i did it somewhere else in code which I should change too)

I went for a more elegant solution in this commit: 035c8cf4505a1ec9cf56c16b4311fee36b97acf6

**Comment by rotsix** [comment]
Arf well played ! thanks mate
