### ISSUE TITLE
rofi-pass does not sleep enough

### ISSUE THREAD

**Issue by AlexDaniel** [carnager/rofi-pass#88]
There are some delays here:
https://github.com/carnager/rofi-pass/blob/6d469c55069e8a175b497fca99918c3982ede19e/rofi-pass#L344-L346

The problem is that these lines are not always reached. Some examples that run without sleeping at all:
https://github.com/carnager/rofi-pass/blob/6d469c55069e8a175b497fca99918c3982ede19e/rofi-pass#L406
https://github.com/carnager/rofi-pass/blob/6d469c55069e8a175b497fca99918c3982ede19e/rofi-pass#L411

I've never noticed this on my other laptop, I'm guessing that it was so slow that it had time to close the window before it was starting to type. On my current machine, however, it always types the first letter into nowhere (e.g. “lexDaniel” instead of “AlexDaniel), and sometimes it manages to mangle the login/password midway. Adding a 0.2 delay to ``autopass`` function resolves most problems for me, but there are many other code paths that need this kind of fix too.

**Comment by carnager** [comment]
i guess i need to make this an option, since it's highly dependent on the machine it's running on.

**Comment by carnager** [comment]
Please test

**Comment by AlexDaniel** [comment]
Yep, that works. Thanks!
